#+TITLE: Segunda sesión de desarrollo Node Js
#+AUTHOR: Jesus Rodolfo Izurieta Veliz

*Primera parte*

Desarrollo de un servidor web que atienda peticiones de archivos con diferentes formatos (ASCII, JSON, HTML, PDF).
Los archivos estarán distribuidos en dos únicos directorios: /pub y /doc).
Cuando el servidor reciba una petición GET con la ruta ‘/doc/', deberá recuperarlo desde el directorio /doc;
el mismo procedimiento deberá seguirse con la ruta ‘/pub'. Por ejemplo: /pub/test.html

El servidor deberá verificar si el archivo solicitado existe antes de recuperarlo,
de lo contrario deberá retornar una página comunicando esta condición de error (Codigo 404 – Not Found).
Use los módulos “http”, “url” y “fs” de Node.

*Segunda parte*

Desarrolle los dos programas que se indican a continuación y redacte un informe que avale las soluciones obtenidas y el trabajo realizado.

1. Cliente para download: Desarrolle un cliente en Java para descargar archivos de su servidor Node.JS. Su programa cliente deberá recibir como argumento la URL del archivo que se desea descargar.
Ejemplo: java miprog http://localhost/doc/miarchivo.pdf
Verifique que la descarga es correcta. Por ejemplo, si el archivo que solicitó es un pdf debería ser abierto por Acrobat.

2. Cliente Node: Probemos ahora, las capacidades de Node.js para desarrollar un programa cliente, escriba un programa en Node.js con las mismas características que el descrito en el apartado anterior. Se sugiere usar los módulos “http”, “url” y “fs”.

* Instrucciones
Clonar el repo e instalar las dependencias con el comando `npm install`, iniciar el servidor con el comando `node app.js` e
ir a `http://localhost:8080` para el servidor http.
